### ISSUE TITLE
Composer cannot find this package

### ISSUE THREAD

**Issue by akkaweb** [iansltx/flightaware-php-client#2]
What you have here looks good for me to use. It cannot be found when installing thru composer, though. I was wondering if you are planning on having it in packagist.org and when you expect that to be done. Thanks alot!

**Comment by iansltx** [comment]
Thought about not showing it there, mainly because it's a tiny project that I don't want folks to blindly rely on. But I went ahead and published it to Packagist. Readme references this as of a8521f3cd3532e13a1bcbc61e6df38a5d0572160.
